### PR TITLE
Modified __init__.py to support initialize AdbClient with custom adb file path

### PR DESCRIPTION
**Pull request by the-eric-kwok**
制作了一个粗浅的魔改，但是没有进行严格的测试，也没有更新版本号。还请大佬海涵🙏
对应的 issue: #54

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
I could see there being a benefit of a user supplying a custom adb binary. Any particular reason why this was closed?

**Comment by codeskyblue** [comment]
Not support custom adb file path with env-var `ADBUTILS_ADB_PATH`

**Comment by ReenigneArcher** [comment]
> Now support custom adb file path with env-var `ADBUTILS_ADB_PATH`

Okay, passing in the path as a variable would be a better option. Not every project using adbutils will be able to (or want to) change the environment variables.

**Comment by codeskyblue** [comment]
use variable will make code a little complicated. em...

**Pull request closed without merging**
